@startuml sequenceDiagram
    actor User1
    User1 -> AppController: opens app
    AppController -> "CookbookAccess : RemoteCookbookAccess": initialize()
    "CookbookAccess : RemoteCookbookAccess" -> RESTAPI: fetchCookbook()
    RESTAPI -> CookbookController : getCookbook()
    CookbookController -> RESTAPI: returns Cookbook as json
    RESTAPI -> "CookbookAccess : RemoteCookbookAccess": returns Cookbook as object
    "CookbookAccess : RemoteCookbookAccess" -> AppController: sets Cookbook as Cookbook object
    AppController -> User1: visualisation over current Cookbook

@enduml