@startuml classDiagramCore

title Class diagram for the core module

class Cookbook{
  -Collection<Recipe> recipes

  +void addRecipe(Recipe recipe
  +void addRecipes(Collection<Recipe> recipes)
  +void removeRecipe(Recipe recipe)

  +Collection<Recipe> filterRecipies(Predicate<Recipe> pred)
  +Collection<Recipe> getRecipes()

}

class Recipe{
  -String name
  -Map<String, String> ingredients
  -String originCountry
  -String description

  -boolean favorite
  -boolean isVegan
  -boolean isGlutenFree
  -boolean isLactoseFree

  -final Collection<String> types

  +Recipe(String name, Map<String, String> ingredients, String originCountry, String type, 
      String description, boolean favorite, boolean isVegan, boolean isGlutenFree, boolean isLactoseFree)
  +Recipe()

  +void setName(String name)
  +void setIngredients(Map<String, String> ingredients)

  +String getOriginCountry()
  +String getDescription()
  +String getName()

  +Map<String, String> getIngredients()
  +void setOriginCountry(String originCountry)
  +void setType(String type)
  +String getType()

  +void setDescription(String description)
  +void addIngredient(String ingredient, String amount)
  +void removeIngredient(String ingredient)

  +boolean isFavorite()
  +void setFavorite(boolean favorite)
  +boolean isVegan()
  +void setVegan(boolean isVegan)
  +boolean isGlutenFree()
  +setGlutenFree(boolean isGlutenFree)
  +boolean isLactoseFree()
  +void setLactoseFree(boolean isLactoseFree)

}

Cookbook "1" --> "*" Recipe : "Contains"
@enduml